"""The no-semantics gate: the browser half may draw, but must not know the language.

Every JavaScript file the page ships is checked, not just playground.js.
intro.js is the reason: it puts glyphs on screen, which makes it the file
most tempted to hold a table of its own, and scoping the gate to one
filename would have let it. Its glyphs come from intro.json, generated by
site/generate_intro.py with the package's own transliterate.

Comments are stripped before checking. The rule is about what the code
DOES, not what its prose is allowed to name — an earlier version grepped
the raw file, so a comment explaining the rule tripped it, and the only
way to pass was to write around the obvious verb.
"""
import pathlib, re, sys

failures = []
site = pathlib.Path(__file__).parent.parent
files = sorted(site.glob("*.js"))
if not files:
    print("no JavaScript found in site/ — the gate is looking in the wrong place")
    sys.exit(1)

for path in files:
    src = path.read_text()
    code = re.sub(r"/\*.*?\*/", "", src, flags=re.S)          # block comments
    code = re.sub(r"^\s*//.*$", "", code, flags=re.M)          # line comments
    code = re.sub(r"(?<![:/])//.*$", "", code, flags=re.M)     # trailing comments

    if re.search(r"[ｦ-ﾝ]", code):
        failures.append(f"{path.name} contains a half-width katakana literal (a glyph table)")
    for name in ["transliterate", "untransliterate"]:
        if re.search(rf"\b{name}\s*\(", code):
            failures.append(f"{path.name} calls {name}()")
    for pattern, what in [(r"\bfunction\s+lex\b", "defines lex()"),
                          (r"\bfunction\s+parse\b", "defines parse()"),
                          (r"\bconst\s+GLYPHS?\b", "declares a glyph table")]:
        if re.search(pattern, code):
            failures.append(f"{path.name} {what}")

if failures:
    print("the browser half owns language logic:")
    for f in failures: print("  -", f)
    sys.exit(1)
print(f"no semantics in the browser half ({len(files)} files)")
